### ISSUE TITLE
Preenchimento do conteúdo da lista de musicas preferidas

### ISSUE THREAD

**Issue by paivafernando** [paivafernando/gcm-impacta#3]
Cada membro do grupo deverá preencher a página docs/musicas.md com suas 5 músicas preferidas.

NÃO EDITEM A PÁGINA NA BRANCH **MASTER**. Crie um novo brach, edite o arquivo e crie um PULL REQUEST quando finalizar.

**Comment by ferpaiva2** [comment]
- 16 toneladas
- Xuxa SPB3
- Carry on wayward son
